<?php

/**
 * @file
 * Paragraphs Aplenty module code.
 */

/**
 * Implements hook_theme().
 */
function paragraphs_aplenty_theme($existing, $type, $theme, $path) {

  $common = array(
    'path' => $path . '/templates',
    'base hook' => 'paragraphs_item',
  );

  return array(
    'paragraphs_item__aplenty_hero' => $common + array(
      'template' => 'paragraphs-item--aplenty-hero',
    ),
    'paragraphs_item__aplenty_media_list' => $common + array(
      'template' => 'paragraphs-item--aplenty-media-list',
    ),
    'paragraphs_item__aplenty_media_block' => $common + array(
      'template' => 'paragraphs-item--aplenty-media-block',
    ),
    'paragraphs_item__aplenty_cards' => $common + array(
      'template' => 'paragraphs-item--aplenty-cards',
    ),
    'paragraphs_item__aplenty_card' => $common + array(
      'template' => 'paragraphs-item--aplenty-card',
    ),
    'paragraphs_item__aplenty_grid' => $common + array(
      'template' => 'paragraphs-item--aplenty-grid',
    ),
    'paragraphs_item__aplenty_column' => $common + array(
      'template' => 'paragraphs-item--aplenty-column',
    ),
    'paragraphs_item__aplenty_column_wrapper' => $common + array(
      'template' => 'paragraphs-item--aplenty-column-wrapper',
    ),
    'paragraphs_item__aplenty_accordion' => $common + array(
      'template' => 'paragraphs-item--aplenty-accordion',
    ),
    'paragraphs_item__aplenty_accordion_item' => $common + array(
      'template' => 'paragraphs-item--aplenty-accordion-item',
    ),
    'paragraphs_item__aplenty_text' => $common + array(
      'template' => 'paragraphs-item--aplenty-text',
    ),
    'paragraphs_item__aplenty_heading' => $common + array(
      'template' => 'paragraphs-item--aplenty-heading',
    ),
    'paragraphs_item__aplenty_image' => $common + array(
      'template' => 'paragraphs-item--aplenty-image',
    ),
  );
}

/**
 * Implements hook_preprocess_paragraphs_item().
 */
function paragraphs_aplenty_preprocess_paragraphs_item(&$variables) {
  $path = backdrop_get_path('module', 'paragraphs_aplenty');
  backdrop_add_css($path . '/css/paragraphs_aplenty.css');
  backdrop_add_js($path . '/js/paragraphs_aplenty.js');

  // Do any extra preprocessing in bundle specific functions.
  $bundle = $variables['paragraphs_item']->bundle();
  $func = '_paragraphs_aplenty_preprocess_' . $bundle;
  if (function_exists($func)) {
    $func($variables);
  }
}

/**
 * Implements hook_preprocess_field().
 */
function paragraphs_aplenty_preprocess_field(&$variables, $hook) {
  // Do any extra preprocessing in field specific functions.
  $field_name = $variables['element']['#field_name'] ?? '';
  $func = '_paragraphs_aplenty_preprocess_' . $field_name;
  if (function_exists($func)) {
    $func($variables);
  }
}

/**
 * Preprocessing code for the Media List bundle.
 */
function _paragraphs_aplenty_preprocess_aplenty_media_list(&$variables) {
  $variables['classes_array'][] = 'aplenty-media_list';
  $variables['aplenty_media_list'] = array();
  if (empty($variables['content']['field_aplenty_paragraphs'])) {
    return;
  }
  $list = entity_metadata_wrapper('paragraphs_item', $variables['paragraphs_item']);
  $media_align = $list->field_aplenty_media_align->value();
  $num_columns = (int)$list->field_aplenty_media_width->value();
  $media_blocks = $list->field_aplenty_paragraphs;
  // The numerator is always 1 for media blocks.
  $class = _paragraphs_aplenty_fraction_to_class(1, $num_columns);
  foreach ($media_blocks as $key => $media_block) {
    $column_id = $media_block->getIdentifier();
    $variables['content']['field_aplenty_paragraphs'][$key]['entity']['paragraphs_item'][$column_id]['#aplenty_media_class'] = $media_align;
    $variables['content']['field_aplenty_paragraphs'][$key]['entity']['paragraphs_item'][$column_id]['#aplenty_width_class'] = $class;
    $variables['aplenty_media_list'][] = $variables['content']['field_aplenty_paragraphs'][$key];
  }
}

/**
 * Preprocessing code for the Media Block bundle.
 */
function _paragraphs_aplenty_preprocess_aplenty_media_block(&$variables) {
  $variables['classes_array'][] = 'aplenty-media_block';
  if (empty($variables['elements']['#aplenty_width_class'])) {
    $variables['elements']['#aplenty_width_class'] = 'col-md-12';
  }
  $variables['classes_array'][] = $variables['elements']['#aplenty_width_class'];
  if (empty($variables['elements']['#aplenty_media_class'])) {
    $variables['elements']['#aplenty_media_class'] = 'aplenty-media-left';
  }
  $variables['classes_array'][] = $variables['elements']['#aplenty_media_class'];
  $variables['content']['field_aplenty_image'][0]['#item']['attributes']['class'][] = 'aplenty-media_block-img';
}

/**
 * Preprocessing code for the Card bundle.
 */
function _paragraphs_aplenty_preprocess_aplenty_card(&$variables) {
  $variables['classes_array'][] = 'aplenty-card';
  if (empty($variables['elements']['#aplenty_width_class'])) {
    $variables['elements']['#aplenty_width_class'] = 'col-md-12';
  }
  $variables['classes_array'][] = $variables['elements']['#aplenty_width_class'];

  $variables['content']['field_aplenty_image'][0]['#item']['attributes']['class'][] = 'aplenty-card-img';
  $paragraph = $variables['paragraphs_item'];
  if (!empty($paragraph->field_aplenty_title)) {
    $variables['content']['field_aplenty_title'][0]['#element']['attributes']['class'] = 'aplenty-card-title';
  }
  if (!empty($paragraph->field_aplenty_body)) {
    $variables['content']['field_aplenty_body'][0]['#element']['attributes']['class'] = 'aplenty-card-body';
  }
  if (!empty($paragraph->field_aplenty_link) && empty($variables['content']['field_aplenty_link'][0]['#element']['attributes']['class'])) {
    $link_classes = 'aplenty-button button button-primary btn btn-primary';
    $variables['content']['field_aplenty_link'][0]['#element']['attributes']['class'] = $link_classes;
  }
}

/**
 * Preprocessing code for the Card title.
 */
function _paragraphs_aplenty_preprocess_field_aplenty_title(&$variables) {
  $variables['items'][0]['#markup'] = '<h2>' . $variables['items'][0]['#markup'] . '</h2>';
}

/**
 * Preprocessing code for the Cards bundle.
 */
function _paragraphs_aplenty_preprocess_aplenty_cards(&$variables) {
  $variables['classes_array'][] = 'aplenty-cards';

  $variables['aplenty_cards'] = array();
  if (empty($variables['content']['field_aplenty_paragraphs'])) {
    return;
  }
  $grid = entity_metadata_wrapper('paragraphs_item', $variables['paragraphs_item']);
  $num_cards = (int)$grid->field_aplenty_card_width->value();
  $card_style_class = $grid->field_aplenty_card_style->value();

  if (empty($card_style_class)) {
    $card_style_class = 'aplenty-card-plain';
  }
  $variables['classes_array'][] = $card_style_class;

  $cards = $grid->field_aplenty_paragraphs;
  // The numerator is always 1 for cards.
  $class = _paragraphs_aplenty_fraction_to_class(1, $num_cards);
  foreach ($cards as $key => $card) {
    $card_id = $card->getIdentifier();
    // @TODO: There is probably a better way to communicate this value to
    // the aplenty_column paragraph.
    $variables['content']['field_aplenty_paragraphs'][$key]['entity']['paragraphs_item'][$card_id]['#aplenty_width_class'] = $class;

    // Copy them to another variable as a quick way to avoid printing
    // the field wrapper.
    $variables['aplenty_cards'][] = $variables['content']['field_aplenty_paragraphs'][$key];
  }
}

/**
 * Preprocessing code for the Heading bundle.
 */
function _paragraphs_aplenty_preprocess_aplenty_heading(&$variables) {
  $variables['classes_array'][] = 'aplenty-heading';
  $variables['heading_text'] = '';
  if (!empty($variables['content']['field_aplenty_heading'])) {
    $variables['heading_text'] = check_url($variables['content']['field_aplenty_heading']['#items'][0]['safe_value']);
  }
  $variables['anchor_text'] = '';
  if (!empty($variables['content']['field_aplenty_anchor'])) {
    $variables['anchor_text'] = check_url($variables['content']['field_aplenty_anchor']['#items'][0]['safe_value']);
  }
}

/**
 * Preprocessing code for the Hero bundle.
 */
function _paragraphs_aplenty_preprocess_aplenty_hero(&$variables) {
  $variables['classes_array'][] = 'aplenty-hero';
  // Set the classes on the button.
  $paragraph = $variables['paragraphs_item'];
  if (!empty($paragraph->field_aplenty_body)) {
    $variables['content']['field_aplenty_body'][0]['#element']['attributes']['class'] = 'aplenty-hero-body';
  }
  if (!empty($paragraph->field_aplenty_link) && empty($variables['content']['field_aplenty_link'][0]['#element']['attributes']['class'])) {
    $link_classes = 'aplenty-button button button-primary btn btn-primary';
    $variables['content']['field_aplenty_link'][0]['#element']['attributes']['class'] = $link_classes;
  }
  // We also need to set the inline CSS for the image.
  if (!empty($variables['content']['field_aplenty_image'])) {
    // Make sure we have a unique ID, in case of multiple Heroes.
    $identifier = 'aplenty-hero-' . $variables['content']['field_aplenty_image'][0]['#item']['fid'];
    $variables['classes_array'][] = $identifier;
    $variables['classes_array'][] = 'aplenty-hero-image';
    // Inline the CSS background image.
    $img = file_create_url($variables['content']['field_aplenty_image'][0]['#item']['uri']);
    $css = ".$identifier.paragraphs-item.aplenty-hero { background-image:url($img); }";
    $variables['content']['field_aplenty_image'] = array(
      '#attached' => array(
        'css' => array(
          array(
            'data' => $css,
            'type' => 'inline',
          ),
        ),
      ),
    );
  }
  else {
    $variables['classes_array'][] = 'aplenty-hero-no-image';
  }
}

/**
 * Helper function to convert a fraction into a grid class.
 *
 * @param int $numerator
 *   The top part of the fraction.
 *
 * @param int $denominator
 *   The bottom part of the fraction.
 */
function _paragraphs_aplenty_fraction_to_class($numerator, $denominator) {
  if ($numerator == $denominator) {
    return 'col-md-12';
  }
  // We could do a lot of fancy math here. But we won't.
  $classes_array = [
    // Denominators first.
    2 => [
      // Then numerators.
      1 => 'col-md-6',
    ],
    3 => [
      1 => 'col-md-4',
      2 => 'col-md-8',
    ],
    4 => [
      1 => 'col-md-3',
      2 => 'col-md-6',
      3 => 'col-md-9',
    ],
    6 => [
      1 => 'col-md-2',
      2 => 'col-md-4',
      3 => 'col-md-6',
      4 => 'col-md-8',
      5 => 'col-md-10',
    ],
    12 => [
      1 => 'col-md-1',
      2 => 'col-md-2',
      3 => 'col-md-3',
      4 => 'col-md-4',
      5 => 'col-md-5',
      6 => 'col-md-6',
      7 => 'col-md-7',
      8 => 'col-md-8',
      9 => 'col-md-9',
      10 => 'col-md-10',
      11 => 'col-md-11',
    ],
  ];
  if (!empty($classes_array[$denominator][$numerator])) {
    return $classes_array[$denominator][$numerator];
  }
  // If still here, it is some weird non-supported fraction.
  return 'col-md-12';
}

/**
 * Preprocessing code for the Grid bundle.
 */
function _paragraphs_aplenty_preprocess_aplenty_grid(&$variables) {
  $variables['classes_array'][] = 'aplenty-grid';
  $grid = entity_metadata_wrapper('paragraphs_item', $variables['paragraphs_item']);
  $max_columns = (int)$grid->field_aplenty_column_width->value();
  $columns = $grid->field_aplenty_paragraphs;
  $num_columns = count($columns);

  // Drop excess columns.
  if ($num_columns > $max_columns) {
    for ($key = $max_columns; $key < $num_columns; $key++) {
      unset($variables['content']['field_aplenty_paragraphs'][$key]);
    }
    $num_columns = $max_columns;
  }

  $stretch = (int)$grid->field_aplenty_column_stretch->value();
  $available_space = $max_columns - $num_columns;
  for ($key = 0; $key < $num_columns; $key++) {

    // The numerator is normally 1.
    $numerator = 1;
    // But one column is allowed to stretch if configured to do so.
    if ($stretch && $stretch == $key + 1) {
      $numerator += $available_space;
    }
    // Finally communicate the class.
    $class = _paragraphs_aplenty_fraction_to_class($numerator, $max_columns);
    $column_id = $columns[$key]->getIdentifier();
    // @TODO: There is probably a better way to communicate this value to
    // the aplenty_column paragraph.
    $variables['content']['field_aplenty_paragraphs'][$key]['entity']['paragraphs_item'][$column_id]['#aplenty_width_class'] = $class;

    // Copy them to another variable as a quick way to avoid printing
    // the field wrapper.
    $variables['aplenty_columns'][] = $variables['content']['field_aplenty_paragraphs'][$key];
  }
}

/**
 * Preprocessing code for the Column bundle.
 */
function _paragraphs_aplenty_preprocess_aplenty_column(&$variables) {
  if (empty($variables['elements']['#aplenty_width_class'])) {
    $variables['elements']['#aplenty_width_class'] = 'col-md-12';
  }
  $variables['classes_array'][] = $variables['elements']['#aplenty_width_class'];
}

/**
 * Preprocessing code for the Column Wrapper bundle.
 */
function _paragraphs_aplenty_preprocess_aplenty_column_wrapper(&$variables) {
  if (empty($variables['elements']['#aplenty_width_class'])) {
    $variables['elements']['#aplenty_width_class'] = 'col-md-12';
  }
  $variables['classes_array'][] = $variables['elements']['#aplenty_width_class'];

  $variables['cards'] = array();
  if (empty($variables['content']['field_aplenty_paragraphs'])) {
    return;
  }
  $content_keys = element_children($variables['content']['field_aplenty_paragraphs']);
  foreach ($content_keys as $key) {
    $pairs[] = $variables['content']['field_aplenty_paragraphs'][$key];
  }
  $variables['column_items'] = $pairs;
}

/**
 * Preprocessing code for the Accordion bundle.
 */
function _paragraphs_aplenty_preprocess_aplenty_accordion(&$variables) {
  $accordion = $variables['paragraphs_item'];
  $accordion = entity_metadata_wrapper('paragraphs_item', $accordion);
  $variables['classes_array'][] = 'aplenty-accordion';

  if ($accordion->field_aplenty_accordion_multi->value()) {
    $variables['classes_array'][] = 'aplenty-accordion-multi';
  }
  else {
    $variables['classes_array'][] = 'aplenty-accordion-single';
  }

  if ($accordion->field_aplenty_accordion_bordered->value()) {
    $variables['classes_array'][] = 'aplenty-accordion-border';
  }
  else {
    $variables['classes_array'][] = 'aplenty-accordion-no-border';
  }

  if ($accordion->field_aplenty_accordion_expand->value()) {
    // @TODO: Presumably there is a more proper way to communicate to the item?
    $first_id = $accordion->field_aplenty_paragraphs[0]->getIdentifier();
    $variables['content']['field_aplenty_paragraphs'][0]['entity']['paragraphs_item'][$first_id]['#aplenty_expand'] = TRUE;
  }

  // Copy to a separate variable for easy rendering without field markup.
  $variables['aplenty_accordion_items'] = array();
  if (!empty($variables['content']['field_aplenty_paragraphs'])){
    foreach (element_children($variables['content']['field_aplenty_paragraphs']) as $key) {
      $variables['aplenty_accordion_items'][] = $variables['content']['field_aplenty_paragraphs'][$key];
    }
  }
}

/**
 * Preprocessing code for the Accordion Item bundle.
 */
function _paragraphs_aplenty_preprocess_aplenty_accordion_item(&$variables) {
  $accordion_item = entity_metadata_wrapper('paragraphs_item', $variables['paragraphs_item']);

  $variables['accordion_title'] = $accordion_item->field_aplenty_title->value();

  $expanded = (!empty($variables['elements']['#aplenty_expand']));
  $variables['expanded'] = ($expanded) ? 'open' : '';
}

/**
 * Preprocessing code for the Text bundle.
 */
function _paragraphs_aplenty_preprocess_aplenty_text(&$variables) {
  $variables['classes_array'][] = 'aplenty-text';
}

/**
 * Preprocessing code for the Image bundle.
 */
function _paragraphs_aplenty_preprocess_aplenty_image(&$variables) {
  $variables['classes_array'][] = 'aplenty-image';
  $variables['caption'] = $variables['content']['field_aplenty_caption'][0];
  $variables['caption_link'] = $variables['content']['field_aplenty_link'][0];
}

/**
 * Helper function to get the required fields for each type.
 *
 * @return
 *   A nested array of bundles to required field names.
 */
function _paragraphs_aplenty_get_required_fields() {
  return array(
    'aplenty_accordion' => array(
      'field_aplenty_accordion_multi',
      'field_aplenty_accordion_bordered',
      'field_aplenty_accordion_expand',
      'field_aplenty_paragraphs',
    ),
    'aplenty_accordion_item' => array(
      'field_aplenty_title',
      'field_aplenty_body',
    ),
    'aplenty_column' => array(
      'field_aplenty_body',
    ),
    'aplenty_column_wrapper' => array(
      'field_aplenty_paragraphs',
    ),
    'aplenty_grid' => array(
      'field_aplenty_column_width',
      'field_aplenty_column_stretch',
      'field_aplenty_paragraphs',
    ),
    'aplenty_hero' => array(
      'field_aplenty_image',
      'field_aplenty_title',
      'field_aplenty_body',
      'field_aplenty_link',
    ),
    'aplenty_media_list' => array(
      'field_aplenty_paragraphs',
      'field_aplenty_media_align',
      'field_aplenty_media_width',
    ),
    'aplenty_media_block' => array(
      'field_aplenty_title',
      'field_aplenty_image',
      'field_aplenty_body',
    ),
    'aplenty_cards' => array(
      'field_aplenty_card_width',
      'field_aplenty_paragraphs',
    ),
    'aplenty_card' => array(
      'field_aplenty_title',
      'field_aplenty_image',
      'field_aplenty_body',
      'field_aplenty_link',
    ),
    'aplenty_heading' => array(
      'field_aplenty_heading',
      'field_aplenty_anchor',
    ),
    'aplenty_image' => array(
      'field_aplenty_image',
      'field_aplenty_link',
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function paragraphs_aplenty_form_field_ui_field_delete_form_alter(&$form) {
  $entity_type = $form['entity_type']['#value'];
  $bundle = $form['bundle']['#value'];
  $field_name = $form['field_name']['#value'];
  if ('paragraphs_item' != $entity_type) {
    return;
  }
  $required = _paragraphs_aplenty_get_required_fields();
  if (empty($required[$bundle])) {
    return;
  }
  if (!in_array($field_name, $required[$bundle])) {
    return;
  }
  $form['paragraphs_aplenty']['#markup'] = t('NOTE: This field is required by Paragraphs Aplenty, and cannot be deleted.');
  $form['actions']['submit']['#access'] = FALSE;
}
