<?php

/**
 * @file
 * Install/update
 */

/**
 * Implements hook_install().
 */
function paragraphs_aplenty_gallery_install() {
  module_load_include('inc', 'paragraphs_aplenty', 'includes/paragraphs_aplenty.crud');

  // Install the Image paragraph type.
  $bundle = 'aplenty_gallery';
  $settings = array(
    'name' => 'Gallery',
    'label' => 'Gallery',
    'description' => 'A gallery of images using Colorbox to provide a convenient way to scroll through images.',
  );
  paragraphs_aplenty_create_bundle($bundle, $settings);
  paragraphs_aplenty_add_image_field('field_aplenty_gallery_image', $bundle, array(
    'label' => 'Gallery Image',
    'required' => TRUE,
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'type' => 'colorbox',
        'settings' => array(
          'colorbox_node_style' => 'thumbnail',
          'colorbox_node_style_first' => 'thumbnail',
          'colorbox_image_style' => '',
          'colorbox_gallery' => 'field_page',
          'colorbox_gallery_custom' => '',
          'colorbox_caption' => 'alt',
          'colorbox_caption_custom' => '',
          'colorbox_multivalue_index' => NULL,
        ),
        'module' => 'colorbox',
        'weight' => 1,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'hidden',
        'type' => 'image',
        'settings' => array(
          'image_style' => 'thumbnail',
          'image_link' => '',
        ),
        'module' => 'image',
        'weight' => 1,
      ),
    ),
  ), array(
    'cardinality' => '-1',
  ));

  // If Paragraphs Aplenty Classy is enabled.
  if (module_exists('paragraphs_aplenty_classy')) {
    list($sets, $styles) = _paragraphs_aplenty_classy_styles();

    $paragraph_types['aplenty_gallery'] = array(
      'background',
      'width',
      'margin',
      'padding',
    );

    foreach ($paragraph_types as $bundle => $paragraph_sets) {
      $fields = array();
      foreach ($paragraph_sets as $set_key) {
        $instance_overrides = array(
          'label' => $sets[$set_key],
          'settings' => array(
            'classy_paragraphs_set' => 'aplenty--' . $set_key,
            'classy_paragraphs_set_include' => 1,
          ),
        );
        _paragraphs_aplenty_classy_add_class_field('field_aplenty_classy_' . $set_key, $bundle, $instance_overrides, array());
        $fields[] = 'field_aplenty_classy_' . $set_key;
      }
      _paragraphs_aplenty_classy_add_field_group($fields, $bundle);
    }
  }

}
