<?php

/**
 * @file
 * Install/update
 */

/**
 * Implements hook_install().
 */
function paragraphs_aplenty_quicktabs_install() {
  module_load_include('inc', 'paragraphs_aplenty', 'includes/paragraphs_aplenty.crud');

  // Install the Quicktab Item paragraph type.
  $bundle = 'aplenty_quicktab_item';
  $settings = array(
    'name' => 'Quicktab item',
    'label' => 'Quicktab item',
    'description' => 'A single quicktab with a title and content. The content can include other paragraph types.',
  );
  paragraphs_aplenty_create_bundle($bundle, $settings);
  paragraphs_aplenty_add_text_field('field_aplenty_title', $bundle, array(
    'label' => 'Quicktab title',
    'required' => TRUE,
  ));
  paragraphs_aplenty_add_paragraphs_field('field_aplenty_paragraphs', $bundle, array(
    'label' => 'Quicktab content',
    'settings' => array(
      'allowed_bundles' => array(
        'aplenty_text' => 'aplenty_text',
        'aplenty_accordion' => 'aplenty_accordion',
        'aplenty_image' => 'aplenty_image',
        'aplenty_quicktabs' => 'aplenty_quicktabs',
      ),
      'title' => 'Paragraph',
      'title_multiple' => 'Paragraphs',
    ),
    'required' => TRUE,
  ));

  // Install the Quicktab paragraph type.
  $bundle = 'aplenty_quicktabs';
  $settings = array(
    'name' => 'Quicktabs',
    'label' => 'Quicktabs',
    'description' => 'Container for quicktabs.',
  );
  paragraphs_aplenty_create_bundle($bundle, $settings);

  paragraphs_aplenty_add_text_list_field('field_aplenty_quicktabs_style', $bundle,
    array(
      'label' => 'Quicktab style',
      'description' => 'Choose the quicktab style to apply to quicktabs.',
      'required' => TRUE,
      'default_value_function' => 'paragraphs_aplenty_quicktabs_styles_default_value',
    ),
    array(
      'settings' => array(
        'allowed_values_function' => 'paragraphs_aplenty_quicktabs_styles_options',
      ),
    )
  );
  paragraphs_aplenty_add_paragraphs_field('field_aplenty_paragraphs', $bundle, array(
    'label' => 'Quicktab Items',
    'settings' => array(
      'allowed_bundles' => array(
        'aplenty_quicktab_item' => 'aplenty_quicktab_item',
      ),
      'title' => 'Quicktab item',
      'title_multiple' => 'Quicktab items',
    ),
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'type' => 'paragraphs_view',
        'weight' => 4,
        'settings' => array(
          'view_mode' => 'full',
        ),
        'module' => 'paragraphs',
      ),
    ),
    'required' => TRUE,
  ));

  // If Paragraphs Aplenty Classy is enabled.
  if (module_exists('paragraphs_aplenty_classy')) {
    list($sets, $styles) = _paragraphs_aplenty_classy_styles();

    $paragraph_types['aplenty_quicktabs'] = array(
      'background',
      'width',
      'margin',
      'padding',
    );

    foreach ($paragraph_types as $bundle => $paragraph_sets) {
      $fields = array();
      foreach ($paragraph_sets as $set_key) {
        $instance_overrides = array(
          'label' => $sets[$set_key],
          'settings' => array(
            'classy_paragraphs_set' => 'aplenty--' . $set_key,
            'classy_paragraphs_set_include' => 1,
          ),
        );
        _paragraphs_aplenty_classy_add_class_field('field_aplenty_classy_' . $set_key, $bundle, $instance_overrides, array());
        $fields[] = 'field_aplenty_classy_' . $set_key;
      }
      _paragraphs_aplenty_classy_add_field_group($fields, $bundle);
    }
  }

}
